11 systems /24/24/24/24/24/24/24/24/24/24/24/
/
4 bars | 0.5 0.5 0.5 0.5 .5 1.5 | 1.6 1.4 .9 | 1.2 1.4 1.4 | 1.6 1.2 1.2 |
|
il0.2      Adagio
=1 treble 2# 3/4 cro d qua rest A qua. B, dsq c d
|
I0.2     tr
rl0.8 Sonata No. 2 in D Major
=1 qua F smq E D min d
|
=1 cro d smq d c d f e d c d
|
=1 qua c smq B A, cro rest rest
/
4 bars | 0.5 0.5 0.5 0.5 .5 1.5 | 0.8 1.2 .55 .45 .45 .45 | 1.2 1.4 1.4 | 1.6 1.2 1.2 |
|
=1 treble cro a qua rest e qua. f dsq g# a
|
=1 qua c smq B A, min d#
|
=1 qua e B smq gn A#, c d e g f e
|
I0.2    tr
=1 qua d smq c B cro e# rest
/
4 bars | 1.3 1.5 2.1 | 1.5 0.9 0.7 | 0.6 1.2 0.6 0.6 0.6 0.6 | 1.4 1.2 1.5 |
|
=1 treble cro f qua rest c smq d f e# f
|
=1 qua A smq G# F min f
|
=1 qua. f dsq g# a smq g f e d c d e c
|
I0.2    tr
=1 qua A# smq G# F cro B smq B, gn f e
/
4 bars | 1 1.2 .9 .7 .5 .8 | 1.5 1.2 | .7 .7 1.0 1.4 | 2 1.6 |
|
I0.3                        tr
=1 treble smq d c d B cro. A# qua B
|
=1 cro B rest rest
|
=1 cro rest qua rest B smq A qua G# dsq F E
|
=1 qua c smq d e min A
/
3 bars | 2 1.5 1.5 | 1.4 1.1 1.1 | 4 |
|
=1 treble smq A, A, B, cn F F G A G F E D
|
=1 qua B, smq cn d min G
|
=1 smq G G A B A, c e d c' B A G
/
4 bars | 4.5 | 2.5 | 4 | 2.5 ||
|
I0.2                         tr
=1 treble smq F B A G cro F qua. E smq D
|
=1 min. D
|
=1 cro. D smq d c d f qua e
|
=1 qua d c min c
/
5 bars | 1.2 0.6 1.2 | 1 0.5 1 | 3 | 2.5 | 1 0.5 1 |
|
il0.2      Allegro
=1 treble 2/4 smq d e cro f smq e d
|
=1 smq c d cro e smq d c
|
=1 smq d A, f A, e A, d A,
|
=1 qua c A, c e
|
=1 smq f g cro a smq g f
/
5 bars | 1.2 0.6 1.2 | 2.4 | 3 | .7 .9 .6 .6 | 1.1 0.7 0.6 0.6 |
|
=1 treble smq e f cro g smq f e
|
=1 qua f d c d
|
=1 smq e d c B A G F E
|
=1 qua D smq d c cro d
|
=1 smq d cn B d g d B G,
/
5 bars | .7 1.1 .5 .5 | 1 .75 .75 .75 | .6 .4 .6 1 | .6 .45 .5 .8 | .6 .7 .75 .75 |
|
=1 treble qua B, smq e d# cro e
|
=1 smq e dn c e a e c e
|
=1 qua f cro f smq e d#
|
=1 qua e cro e smq dn c
|
=1 qua d smq c B A G F E
/
4 bars | 4.3 | 1 .8 1 1 | 4 | 1 .7 1 1 |
|
=1 treble smq F G A F D F G A
|
=1 smq B, c qua d smq d c B A,
|
=1 smq G# A B' G E G A B'
|
=1 smq c d qua e smq e d c B
/
5 bars | 4.4 | 1 .7 1 1 | 4 | 1 1 0.7 1 | .7 .7 .7 .9 |
|
=1 treble smq A B c' A F A B c'
|
=1 smq d e qua f smq f d e f
|
=1 smq G# A B G E G B d'
|
I0.4                     tr
=1 smq c d e f qua. B' smq A
|
=1 cro A qua rest e

12 systems /24/24/24/24/24/24/24/24/24/24/24/24/
/
5 bars | 1.1 1.1 .9 .9 | 1 1 .8 .8 | .9 .9 .9 1.3 | .7 .7 1 1.3 | 1.2 .7 .6 0.9 |
|
=1 treble smq e g f e qua d d
|
=1 smq d B G#, B qua C c'
|
=1 smq c e c A, F d' B G#
|
=1 cro E smq rest E F G#
|
=1 smq A B cro cn smq B' A
/
7 bars | 1.1 .7 .7 1 | 0.7 1 1 1 | 2.1 :||: 1.8 | 1.8 | 1.8 | 1.8 |
|
=1 treble smq G# A cro B smq A G
|
=1 qua e smq d c d c B c
|
=1 min A
|
=1 min rest
|
=1 min rest
|
=1 min rest
|
=1 min rest
/
4 bars | 1.3 1 .8 1.1 | 3.9 | 1.3 .9 .9 .9 | 4 |
|
=1 treble smq A B cro cn smq B' A
|
=1 smq G F E D E F G A
|
=1 smq B, cn d e d c B A,
|
=1 smq cn B A, B G, B d g
/
5 bars | 3.4 | .6 1 .6 .6 .6 .6 | 3 | .8 .8 1.2 .8 | 2 1.7 |
|
=1 treble qua e G, cn e
|
=1 smq e d cn B A, B c e
|
=1 qua d# B, F, f
|
=1 qua f B smq e f qua g
|
=1 smq g f e d qua c f
/
4 bars | 2 1.7 | 2 1.8 | 1.1 .8 .8 1.1 | 1.3 .9 .9 .9 |
|
=1 treble smq f e d c qua B g
|
=1 smq g A#, B c qua F A#
|
=1 smq B c cro d smq c B
|
=1 smq A G# F E F G A B
/
5 bars | 4.4 | 2 1.5 | .8 1 .8 .8 | 4 | 1.7 1.5 |
|
=1 treble smq c d e f e d c B
|
=1 smq d c B c cro A
|
=1 qua rest smq e f qua g rest
|
=1 qua rest smq f g f e d c
|
=1 qua d f cro b
/
5 bars | 1.5 1.3 1.1 1 | 2.6 | 1.3 .8 .8 1.1 | 1.3 .9 .9 1.3 | 3 |
|
I0.4                         tr
=1 treble smq b g# a f qua. e# smq f
|
=1 min f
|
=1 smq f gn cro a smq g f
|
=1 smq e f cro g smq f e
|
I0.2               tr
=1 qua f d c d
/
4 bars | 4.3 | 4 | 4 | 4 |
|
=1 treble smq e d c B A G F E
|
=1 smq D E F E D F A d'
|
=1 smq c d e d c e A, c
|
=1 smq d A, f A, e A, d A,
/
4 bars | 4 | 1 1 1 1.3 | 1.3 .9 1 1 | 4.3 |
|
=1 treble smq c d e d c' B A G
|
=1 smq F G A F D F A cn'
|
=1 smq B, cn qua d smq d' D E F
|
=1 smq G A B G E G B d'
/
5 bars | 1.1 .9 1.1 1.1 | .9 .75 .75 1 | .9 .75 .75 1 | .8 1 1 1 | 1.5 1.7 1 |
|
=1 treble smq c d qua e smq e e f g
|
=1 qua a cro a smq g f
|
=1 qua g cro g smq f e
|
=1 qua f smq e d f e d c
|
=1 smq d' A F D cro cn
/
4 bars | 2.1 1.8 | 2 1.7 | 2 1.7 | 1 1 1.1 1.2 |
|
=1 treble smq cn' A F D cro B
|
=1 qua B' smq G E cro A
|
=1 qua A smq F D cro G
|
=1 smq G, A, c e a g fn e
/
4 bars | 1.3 .9 .9 1.3 | 1.3 .8 .8 1.2 | 1.2 1 .8 .9 | 3 :||
|
=1 treble smq fn g cro a smq g f
|
=1 smq e fn cro g smq f# e
|
=1 smq g f# e d qua A, c#
|
=1 min d
